<?php

/**
 * @file
 * Contains product_rest_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function product_rest_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the product_rest_api module.
    case 'help.page.product_rest_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Rest API for Product Entity') . '</p>';
      return $output;

    default:
  }
}

function product_rest_api_cron() {

   //hold the time that cron run last time
   $expires = \Drupal::state()->get('product_rest_api.cron_last_run',REQUEST_TIME);
   try {
     $client = \Drupal::httpClient();
     $response = $client->get('http://chroniclingamerica.loc.gov/awardees.json', ['headers' => [
        'Accept'     => 'application/json',
        'http_errors' => false,
        ]
    ]);
     //  $request = $client->createRequest('GET', 'http://chroniclingamerica.loc.gov/newspapers.json');
      $status =  $response->getStatusCode();
      $reason =  $response->getReasonPhrase();
      $header1 = $response->getHeader('Content-Type');
      $header2 = $response->getHeader('Last-Modified');
      if($status==200 && $reason=="OK") {
        $properties = json_decode($response->getBody()->getContents(), true);
        // $response->getBody()->seek(count($properties));
      }
   }catch(RequestException $ex) {
     \Drupal::logger('product_rest_api')->notice($ex);
   }catch(InvalidArgumentException $ex) {
     \Drupal::logger('product_rest_api')->notice($ex);
   }
//
//   // Long-running operation example, leveraging a queue:
//   // Queue news feeds for updates once their refresh interval has elapsed.
//   $queue = \Drupal::queue('products_consumer');
//   $ids = \Drupal::entityManager()->getStorage('products')->getFeedIdsToRefresh();
//   foreach (Feed::loadMultiple($ids) as $feed) {
//     if ($queue->createItem($feed)) {
//       // Add timestamp to avoid queueing item more than once.
//       $feed->setQueuedTime(REQUEST_TIME);
//       $feed->save();
//     }
//   }
//   $ids = \Drupal::entityQuery('products')
//     ->condition('queued', REQUEST_TIME - (3600 * 6), '<')
//     ->execute();
//   if ($ids) {
//     $feeds = Feed::loadMultiple($ids);
//     foreach ($feeds as $feed) {
//       $feed->setQueuedTime(0);
//       $feed->save();
//     }
//   }
}
/**
 * Implements hook_theme().
 */
function product_rest_api_theme() {
  return [
    'product_rest_api' => [
      'render element' => 'children',
    ],
  ];
}
