
product_rest_api.rest_consume_controller_hello:
  path: '/product_rest_api/rest/test/{id}'
  defaults:
    _controller: '\Drupal\product_rest_api\Controller\RestConsumeController::get'
    _title: 'restConsume'
    id: ' '
    api: rest_api
  requirements:
    _permission: 'access content'
    id: '^[0-9_]+'
